trigger:

  - master

resources:

  containers:

  - container: mvn3_jdk8

    image: maven:3-jdk-8

container: mvn3_jdk8

steps:

- task: Maven@3

  inputs:

    mavenPomFile: 'pom.xml'

    mavenOptions: '-Xmx3072m'

    jdkArchitectureOption: 'x64'

    publishJUnitResults: true

    testResultsFiles: '**/surefire-reports/TEST-*.xml'

    goals: 'package'

- task: CopyFiles@2

  inputs:

    SourceFolder: '$(agent.builddirectory)/s/target'

    Contents: '**'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

  

- task: PublishBuildArtifacts@1

  inputs:

    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

    ArtifactName: 'drop'

    publishLocation: 'Container'