variables:
  
  artifactName: my-app-1.0-SNAPSHOT 

trigger:

  - master

resources:

  containers:

  - container: mvn3_jdk8

    image: maven:3-jdk-8

  # - container: dind
    
  #   image: docker:dind # cant be used due azure devops limitations

jobs:

- job: Build
  
  pool:

    name: Draft pool

  container: mvn3_jdk8

  steps:

  - task: Maven@3

    inputs:

      mavenPomFile: 'pom.xml'

      mavenOptions: '-Xmx3072m'

      jdkArchitectureOption: 'x64'

      publishJUnitResults: true

      testResultsFiles: '**/surefire-reports/TEST-*.xml'

      goals: 'package'

  - task: CopyFiles@2

    inputs:

      SourceFolder: '$(agent.builddirectory)/s/target'

      Contents: '**'

      TargetFolder: '$(Build.ArtifactStagingDirectory)'  

  - task: PublishBuildArtifacts@1

    inputs:

      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

      ArtifactName: 'drop'

      publishLocation: 'Container'
  
  - task: CopyFilesOverSSH@0
  
    inputs: 
      sshEndpoint: deployServerSshServiceConnection
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      contents: '$(artifactName).jar' 
      targetFolder: /opt/release/
      cleanTargetFolder: false 
      overwrite: true 

- job: deployRelease
  
  steps:

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: java -jar /opt/release/$(artifactName).jar

  
#  steps: 
  

# - job: dockerBuildAndPublish
  
#   pool:

#     name: Draft pool

#   container: dind

#   steps: 
    
#   - task: Docker@2

#     inputs:
    
#       command: login
    
#       containerRegistry: foxDockerHubServiceConnection

#   - task: Docker@2

#     inputs:

#       command: buildAndPush

#       Dockerfile: ./Dockerfile

#       buildContext: '$(Build.ArtifactStagingDirectory)'

#       repository: foxlollato/java-maven-hw

#       tags: sometag1